# Используем официальный образ Ubuntu как базовый
FROM ubuntu:22.04

# Установка необходимых пакетов
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    pkg-config \
    libgmp-dev \
    libmpfr-dev \
    libeigen3-dev \
    libssl-dev \
    doxygen \
    graphviz \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Установка Google Test Framework
RUN git clone https://github.com/google/googletest.git /tmp/googletest \
    && cd /tmp/googletest \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make install \
    && rm -rf /tmp/googletest

# Настройка рабочей директории
WORKDIR /app

# Копирование исходного кода
COPY . /app

# Сборка проекта
RUN mkdir build \
    && cd build \
    && cmake .. \
    && make

# Установка как точки входа
ENTRYPOINT ["/app/build/toruscsidh"]
